image: gitlab.inovexcorp.com:4567/ilab/docker-images/maven-node-jdk8

before_script:
  - PRIVATE_URL="$(echo $CI_PROJECT_URL | sed "s|https://|https://gitlab-ci-token:$ACCESS_TOKEN@|g").git"
  - git remote set-url origin $PRIVATE_URL
  - git config --global user.email 'gitlab.runner@inovexcorp.com'
  - git config --global user.name 'Gitlab Runner'

stages:
  - create_release_branch
  - new_release_deploy

create_release_branch:
  stage: create_release_branch
  only:
    - /release\/\d+\.\d+/
  except:
    - branches
  script:
    - git tag -d $CI_COMMIT_TAG
    - git push origin :$CI_COMMIT_TAG
    - git checkout -b $CI_COMMIT_TAG
    - git push origin $CI_COMMIT_TAG
    # - git remote add github git@github.com:inovexcorp/mobi.git
    - git remote add github https://jaydenne:$JESSE_GITHUB_TOKEN@github.com/jaydenne/gitlab-test.git
    - git push github HEAD:master
    - git push github HEAD:$CI_COMMIT_TAG
